---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@v6

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"
      - run: go test -v ./...
